### ISSUE TITLE
tiddler 可以用文件路径管理 更加清晰

### ISSUE THREAD

**Issue by FXTD-ODYSSEY** [tiddly-gittly/Tiddlywiki-NodeJS-Github-Template#30]
$:/config/FileSystemPaths

这个文件加上下面的分类

[is[system]!has[draft.of]removeprefix[$:/]addprefix[_system/]]

node.js 就会将系统内置的文件 按文件夹保存

![image](https://user-images.githubusercontent.com/40897360/147489750-30a7fadb-1d88-4b1e-89b3-32a4c98d8751.png)

从 xp 框架那里学来的
https://keatonlao.github.io/tiddlywiki-xp/#FileSystemPaths

**Comment by linonetwo** [comment]
不错的教程站，已收录到 https://tw-cn.netlify.app/

**Comment by linonetwo** [comment]
这个方案目前在 tidgi 里用于实现子 wiki 私有内容

**Comment by linonetwo** [comment]
你要有兴趣也可以来一起编辑中文教程

**Comment by FXTD-ODYSSEY** [comment]
好呀，向大佬学习~
