### ISSUE TITLE
提供多个模板选择

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/Tiddlywiki-NodeJS-Github-Template#52]
不知道能不能提供多个模板选择，比如空白模板。不知道是在太记的仓库里提，还是在这边提。

多个模板的话，不仅可以放空白模板，也可以放一个简略的测试模板，也就是有一些基本插件，这样测试新内容时不用排除太多插件问题。当然也可以放其他用户来添加新模板。

还是说一个模板就需要一个仓库？

**Comment by linonetwo** [comment]
看 https://github.com/tiddly-gittly/Awesome-TiddlyWiki-Editions ，还没人搞

**Comment by dongrentianyu** [comment]
也就是说，我们不需要在太记新建wiki时选择模板，而是能够像安装插件一样通过类似cpl一样的东西来安装模板？

**Comment by linonetwo** [comment]
其实都可以啊，但不管什么都依赖那个东西
