### ISSUE TITLE
如何减少页面上的按钮？

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/Tiddlywiki-NodeJS-Github-Template#56]
我看好像并没有减少按钮的方式。

因为太记预置了一些插件，所以减少按钮只能通过增加config条目来控制。要这样做然后加入到仓库里吗？

**Comment by linonetwo** [comment]
把配置加到 https://github.com/tiddly-gittly/itonnote-plugin 里吧

**Comment by linonetwo** [comment]
目前应该够少了，不过我自己的wiki里还是把命令菜单的加回去了，不然移动端点起来不方便
