### ISSUE TITLE
增加$:/NPL插件库

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/Tiddlywiki-NodeJS-Github-Template#61]
他专门做了一个插件库，这样也好。有了插件安装和更新就方便很多。

[链接](https://neotw.oeyoewl.top/#%24%3A%2FNPL)

**Comment by linonetwo** [comment]
可以加一个，就是这是 Github pages 的，不一定有 CPL 快

**Comment by dongrentianyu** [comment]
因为我不知道为啥fork下来的仓库，用`pnpm run dev`命令进不去。就没法实际上的调整。

**Comment by linonetwo** [comment]
或者在 CPL 定期导入这个插件源也可以，有一个 npm script 可以导入，输入 html 地址就可以

**Comment by linonetwo** [comment]
要先 pnpm i 成功

**Comment by dongrentianyu** [comment]
pnpm i 是成功了的。或者我删除了重新克隆一下试试。

**Comment by dongrentianyu** [comment]
![image](https://github.com/tiddly-gittly/Tiddlywiki-NodeJS-Github-Template/assets/109711900/20782275-9d59-47f5-a37a-ff125ff81985)

好吧，仍然不成功。

**Comment by linonetwo** [comment]
这种小问题你问gpt吧，或者打开packagejson看看就知道了。

**Comment by linonetwo** [comment]
可以看看 CPL 导入这个了没有，如果没有可以帮忙填一下那个 library 。json
