### ISSUE TITLE
gh-pages不能正常发布

### ISSUE THREAD

**Issue by dongrentianyu** [tiddly-gittly/Tiddlywiki-NodeJS-Github-Template#77]
Version v0.9.3

Electron Version: 28.1.0
Node Version: 18.18.2
Chromium Version: 120.0.6099.109

以上是太记版本中自带的模板。里面的gh-pages不能正常发布。报错截图如下。

![image](https://github.com/tiddly-gittly/Tiddlywiki-NodeJS-Github-Template/assets/109711900/9940c2f0-fdd0-4193-98d3-04c42e05ea15)

而当我把gh-pages文件回退到之前的版本时，就能成功发布了。

![image](https://github.com/tiddly-gittly/Tiddlywiki-NodeJS-Github-Template/assets/109711900/f3a93c5d-90cf-4825-a6c5-4d84d60971dd)

红色的是不能发布的版本。绿色的是之前的版本，能正常发布网址。

**Comment by linonetwo** [comment]
我都升级了一下，就修好了，你可以复制这个仓库里的最新版

**Comment by dongrentianyu** [comment]
ok，可以了
